package com.netcracker.project.model;

import com.netcracker.project.model.entity.Comment;
import java.math.BigInteger;
import java.util.Collection;

public interface CommentDAO {

  void createComment(Comment comment);

  void deleteCommentFromTask(BigInteger commentId, BigInteger taskId);

  void updateCommentBody(String commentBody, BigInteger commentId);

  Collection<Comment> getCommentsForTask(BigInteger taskId);

  String CREATE_COMMENT = "INSERT ALL " +
      "INTO OBJECTS (OBJECT_ID,PARENT_ID,OBJECT_TYPE_ID,NAME,DESCRIPTION, OBJECT_VERSION) VALUES (OBJECT_SEQUENCE.NEXTVAL,NULL,9,'Comment' || OBJECT_SEQUENCE.CURRVAL,NULL, 1) " +
      "INTO ATTRIBUTES (ATTR_ID,OBJECT_ID,VALUE,DATE_VALUE,LIST_VALUE_ID) VALUES (66,OBJECT_SEQUENCE.CURRVAL,?,NULL,NULL) " +
      "INTO ATTRIBUTES (ATTR_ID,OBJECT_ID,VALUE,DATE_VALUE,LIST_VALUE_ID) VALUES (67,OBJECT_SEQUENCE.CURRVAL,NULL,?,NULL) " +
      "INTO OBJREFERENCE (ATTR_ID, OBJECT_ID, REFERENCE) VALUES (68, OBJECT_SEQUENCE.CURRVAL, ?)" +
      "INTO OBJREFERENCE (ATTR_ID, OBJECT_ID, REFERENCE) VALUES (69, OBJECT_SEQUENCE.CURRVAL, ?)" +
      "SELECT * " +
      "FROM Dual";

  String DELETE_COMMENT_FROM_TASK =
      " DELETE FROM OBJREFERENCE WHERE OBJECT_ID = ? AND REFERENCE = ? ";

  String UPDATE_BODY_COMMENT =
     " UPDATE ATTRIBUTES " +
     " SET ATTRIBUTES.VALUE = ? " +
     " WHERE ATTRIBUTES.OBJECT_ID = ? AND " +
     " ATTRIBUTES.ATTR_ID = 66 ";

  String GET_ALL_COMMENTS_FOR_TASK =
      "   SELECT COMMENTS.OBJECT_ID AS COMMENT_ID, COMMENT_BODY.VALUE AS COMMENT_BODY, COMMENT_DATE.DATE_VALUE AS COMMENT_DATE, "
      + " USER_ID_REF.REFERENCE AS USER_ID, TASK_ID_REF.REFERENCE AS TASK_ID "
      + " FROM OBJECTS COMMENTS, OBJECTS TASK, "
      + " ATTRIBUTES COMMENT_BODY, ATTRIBUTES COMMENT_DATE, "
      + " OBJREFERENCE USER_ID_REF, OBJREFERENCE TASK_ID_REF "
      + " WHERE COMMENTS.OBJECT_TYPE_ID = 9 AND TASK.OBJECT_ID = ? AND "
      + " TASK.OBJECT_TYPE_ID = 3 AND "
      + " COMMENT_BODY.ATTR_ID = 66 AND "
      + " COMMENTS.OBJECT_ID = COMMENT_BODY.OBJECT_ID AND "
      + " COMMENT_DATE.ATTR_ID = 67 AND "
      + " COMMENTS.OBJECT_ID = COMMENT_DATE.OBJECT_ID "
      + " AND USER_ID_REF.OBJECT_ID = COMMENTS.OBJECT_ID "
      + " AND USER_ID_REF.ATTR_ID = 68 "
      + " AND TASK.OBJECT_ID = TASK_ID_REF.REFERENCE "
      + " AND TASK_ID_REF.OBJECT_ID = COMMENTS.OBJECT_ID "
      + " AND TASK_ID_REF.ATTR_ID = 69 ";

}
