CREATE TABLE PROJECT_SPRINT_STAT (
    PROJECT_ID NUMBER(20) NOT NULL,
    SPRINT_ID NUMBER(20) NOT NULL,
    SPRINT_NAME VARCHAR(30) NOT NULL,
    SPRINT_START_DATE VARCHAR(30) NOT NULL,
    SPRINT_END_DATE VARCHAR(30) NOT NULL,
    SPRINT_PLANNED_END_DATE VARCHAR(30) NOT NULL
);

CREATE TABLE PROJECT_USER_TASK_STAT(
    PROJECT_ID NUMBER(20) NOT NULL,
    USER_ID NUMBER(20) NOT NULL,
    TASK_ID NUMBER(20) NOT NULL,
    TASK_PRIORITY VARCHAR2(30) NOT NULL,
    TASK_STATUS VARCHAR(30) NOT NULL,
    START_DATE VARCHAR(30) NOT NULL
);

CREATE TABLE USER_WORKING_HOURS_STAT (
    WORKING_DAY_ID NUMBER(20) NOT NULL,
    USER_ID NUMBER(20) NOT NULL,
    WEEK_NUMBER NUMBER(20) NOT NULL,
    WORKING_DAY_DATE VARCHAR2(20) NOT NULL,
    HOURS_COUNT NUMBER(20) NOT NULL,
    WORKING_DAY_STATUS VARCHAR(20) NOT NULL
);

CREATE TABLE WORK_PERIOD_STAT(
    WORK_PERIOD_ID NUMBER(20) NOT NULL,
    USER_ID NUMBER(20) NOT NULL,
    PROJECT_ID NUMBER(20) NOT NULL,
    START_DATE    VARCHAR(30) NOT NULL,
    END_DATE    VARCHAR(30) NOT NULL,
    STATUS VARCHAR(30) NOT NULL
);

CREATE TABLE VACATION_STAT(
    VACATION_ID NUMBER(20) NOT NULL,
    USER_ID NUMBER(20) NOT NULL,
    PM_ID  NUMBER(20) NOT NULL,
    LM_ID  NUMBER(20) NOT NULL,
    PROJECT_ID NUMBER(20) NOT NULL,
    START_DATE    VARCHAR(30) NOT NULL,
    END_DATE    VARCHAR(30) NOT NULL,
    PM_APPROVE_STATUS VARCHAR(30) NOT NULL,
    LM_APPROVE_STATUS VARCHAR(30) NOT NULL
);

CREATE TABLE OBJECT_VERSION_TEMP(
    OBJECT_ID NUMBER(20) NOT NULL,
    OBJ_TYPE_ID NUMBER(20) NOT NULL,
    VERSION NUMBER(20) NOT NULL
);